// Generated by tools/audio-manifest.mjs — do not edit. true == file exists in public/audio/.
export const AUDIO = {
  "music": true,
  "vo-1-snap": true,
  "vo-2-log": true,
  "vo-3-nutrition": true,
  "vo-4-ask": true,
  "vo-5-logo": true
} as const;
